# Generated by Django 2.2.8 on 2020-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'Equipment'), ('FW', 'Footwear'), ('A', 'Accessories'), ('C', 'Clothes')], max_length=2),
        ),
    ]
