# Generated by Django 2.2.8 on 2020-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200827_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'Equipment'), ('FW', 'Footwear'), ('A', 'Accessories'), ('C', 'Clothes'), ('SW', 'Sportwears'), ('S', 'Shirt')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
